travis:
  secure:
    BINSTAR_TOKEN: Cj1txXu68jWOSI4MUSsJ1PeNdIUIytz+7tuA7x94IH7YYC+UwTN40riDf8vVxexDQg+UhvNJ/17E6bkDKZqZfb2F0Z8RnbNNc5Omuftcjzmj3oWs76jlqs8/JS8kIZkj0IlwkHsbcX/dYXcsBDEIrEEanTZLKZZMh5dkqz4LjCGTLZkd5vCNQ6SB0y/WW214sYmMGR+CmKfOa0+dnTPLrHYoB4/JG23dx2NkLgHhqIYkAxAey1WrQ5Y70E0f724B8YEX4AoVH2cuDg4YDTE5e6fgEpAtNK4p8H/Qg7Eb8aoH2KLmQbqFrYfJ5BWHhba1n3rPHsxflwBpWyLepmMfGTTjXzOdqpAZmOHWIYUr8/9F7Hygt1TZHrnXuyuA6MuyTC2bzKQtYl4xqUVD47dMR/I73FZYx+UDyHdV2/Dc4P/3AEYRw1vBW5K8KmNgSsKYewk7OAC7f0vhb4TF8HznehBuHfrhuFUEjqTmE1402+G7bcnn2ouliwlVb2voXeA+9xy252NrDjQlUAxZILWcQxd7mxO4Mc+jRkFY4D956KymWKSOg6roPwGy40aEZPL9JL/ce70aVZYROPUxJ4au8sd3QosdXsaBMumr9lVA0Q7SnZSFPGz/foHmZx5qHL0E9CS+NKE+09k7AimLbUagGNWpcVfSM0lWm51bDsxpd3Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
