travis:
  secure:
    BINSTAR_TOKEN: Za2lw/7vGBPpjHpMfAL0iUQRD2ue+seNdg4jHvLRhGFfnan6GAf5buSzgHdB7YfVrAi7wH8WujGqix53s8g8GWoYg+6V++D0AhdDTDgCsgvlDaqV9ijKTTSKYXGzys82uWsO9+QrE9j8OF0JVTSYfmD4ZXp9X30xQj8DlMyR536fVcNnkNwDakOGNcBHw8ihGS5SbpPJfHWVrnT/G2XlwP4QnOosxBtmE2YqAqMzXGkOi/J0hMWn6Z9o9Jd6MvDMp24AiT5CH7urWjHonW176jOxWtZVcWR/95Hf8YtYKvKkuSlMwlxUQZkHXiBIooYaHV4coMByxJBgiluh1nczOfnQxCYqsGA9tkNjxFZdrCU+B2SMdZjeqGriDczJhHyHb/8szlvIPMs3Wx4KdB/SZhqrzfkQOD5TRvbgh15Q+OEDQfJMZ+KF3ZLLPEu31JUNbJHZ/DuDjEsd8Z1CnQgxf3UEqgsGysLtuXnyoQzPQ/UN9K/uSBQ5Z159VknzvhbQ1P+rd7LbhVOHwDMY0fObjWFAvfvUpo26zkwzTtbZGiYysJ896F4VUIAxueB/sEbSeF5ZfhiyfZjoCp970GOdqE3EGSfDPq+P/l7EZuvcTtw+3rKGaQO4KvoiaCpCJaSXqA75QI2KFUTJJIc3HrrSCG4dr5XGvNyO1Az9NQ+GvCI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
